blank_issues_enabled: false
contact_links:
  - name: Security Policy
    url: https://github.com/SAP/pull-request-semver-bumper/security/policy
    about: Please do not report security vulnerabilities in public issues.
  - name: Ask a question
    url: https://github.com/SAP/pull-request-semver-bumper/discussions/new?category=q-a
    about: Ask a question or get help with using the project.
